package com.parc.domain.enums;

public enum TypeNotification {
    MISSION_ASSIGNEE,
    MISSION_MODIFIEE,
    MISSION_ANNULEE,
    MAINTENANCE_PROGRAMMEE,
    MAINTENANCE_IMMINENTE,
    MAINTENANCE_URGENCE,
    CONGE_DEMANDE,
    CONGE_APPROUVE,
    CONGE_REFUSE,
    EXPIRATION_ASSURANCE,
    EXPIRATION_CARTE_GRISE,
    EXPIRATION_VISITE_TECHNIQUE,
    DEPASSEMENT_CONSOMMATION,
    ACCIDENT_DECLARE,
    AMENDE_DECLAREE,
    PANNE_CRITIQUE,
    ALERTE_GENERALE
}